[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',    
    '@chainlink/local/=lib/chainlink-local/',
]

[rpc_endpoints]
sepolia = "${ALCHEMY_SEPOLIA_API_URL}"

etherscan_api_key = "${ETHERSCAN_API_KEY}"
private_key = "${PRIVATE_KEY}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
